[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "fRprMGtWFJ9oGAjCedCc9xSfZoQfWZm43Z2pp29z5ML"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/cashmunsy/.config/solana/id.json"
rpc = "http://localhost:9900"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
